"use client"

import { createContext, useContext, useEffect, useState, type ReactNode } from "react"

type Language = "en" | "es" | "ru"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    "nav.home": "Home",
    "nav.about": "What I Do",
    "nav.projects": "Projects",
    "nav.skills": "Skills",
    "nav.experience": "Experience",
    "nav.contact": "Contacts",
    "hero.title": "Victoria Nasonova",
    "hero.subtitle": "Frontend Developer",
    "hero.description": "I develop responsive web interfaces with a focus on clean code, performance, and user experience.",
    "about.title": "What I Do",
    "about.description": "• Frontend Development\n• AI-Assisted Development\n• API Integration & Automation\n• UI Implementation",
    "about.item1": "I create responsive, user-friendly web interfaces. My focus is on building clear, maintainable, and high-performance solutions that look great and work seamlessly on any device.",
    "about.item2": "I design and develop scalable applications and landing pages using AI tools to accelerate development and improve efficiency. I integrate solutions with backend services for secure data management and automation.",
    "about.item3": "I connect applications and services through API integrations. These automations help optimize workflows, synchronize data, and reduce repetitive manual work for teams.",
    "about.item4": "I transform Figma designs into production-ready interfaces with attention to detail, accessibility, and pixel perfection. I care about usability and consistency across all screens and devices.",
    "about.card1.title": "Frontend Development",
    "about.card2.title": "AI-Assisted Development",
    "about.card3.title": "API Integration & Automation",
    "about.card4.title": "UI Implementation",
    "skills.title": "Skills & Tools",
    "skills.description": "Frontend:\nJavaScript • TypeScript • React • Next.js • HTML5 • CSS3 • TailwindCSS • Vite\n\nTesting & Code Quality:\nESLint • Prettier • Vitest • React Testing Library • Git & GitHub\n\nNo-Code & Automation:\nBubble • Tilda • WeWeb • Carrd • Xano • Airtable • Make\n\nDesign & Collaboration:\nFigma • Design Systems • Responsive Layouts",
    "skills.certificates": "Certificates & Achievements",
    "experience.title": "Experience & Education",
    "experience.description": "Frontend Developer — ATLAS ANALYTICS (1 year)\n\n• Redesigned and rebuilt the company website from scratch, migrating it from a no-code platform to a modern stack using Next.js, improving performance, scalability, and overall user experience.\n• Designed and developed partner websites end-to-end — from selecting UI/UX concepts to implementing interfaces and integrating backend services and automation workflows.\n• Improved the UX and consistency of internal applications by restructuring interfaces, unifying design patterns, and enhancing usability across key features.\n• Built dashboards and reporting tools by working with data from backend systems, and automated data delivery to internal teams to support decision-making processes.\n• Collaborated within a team environment on real-world projects, contributing to both product improvements and new feature development.\n\nRS School — JavaScript / Frontend / React (1.5 years)\n\nCompleted an intensive frontend development program.\n\n• Worked with HTML, CSS, JavaScript, TypeScript, React, and Next.js.\n• Built applications from scratch using modern tooling (Vite, Webpack) and integrated REST APIs using asynchronous JavaScript.\n• Implemented state management (Context API, Redux, Zustand), routing, and data fetching.\n• Used ESLint and Prettier to maintain code quality, and gained experience with testing basics, debugging, and performance optimization.\n• Collaborated in team-based projects, participated in code reviews, and followed Agile practices.",
    "experience.item1": "Frontend Developer — ATLAS ANALYTICS (1 year)\n\n• Redesigned and rebuilt the company website from scratch, migrating it from a no-code platform to a modern stack using Next.js, improving performance, scalability, and overall user experience.\n• Designed and developed partner websites end-to-end — from selecting UI/UX concepts to implementing interfaces and integrating backend services and automation workflows.\n• Improved the UX and consistency of internal applications by restructuring interfaces, unifying design patterns, and enhancing usability across key features.\n• Built dashboards and reporting tools by working with data from backend systems, and automated data delivery to internal teams to support decision-making processes.\n• Collaborated within a team environment on real-world projects, contributing to both product improvements and new feature development.",
    "experience.item2": "Completed an intensive 1.5-year frontend development program at RS School\n\n• Worked with HTML, CSS, JavaScript, TypeScript, React, and Next.js.\n• Built applications from scratch using modern tooling (Vite, Webpack) and integrated REST APIs using asynchronous JavaScript.\n• Implemented state management (Context API, Redux, Zustand), routing, and data fetching.\n• Used ESLint and Prettier to maintain code quality, and gained experience with testing basics, debugging, and performance optimization.\n• Collaborated in team-based projects, participated in code reviews, and followed Agile practices.",
    "contact.title": "Get In Touch",
    "contact.description": "Let's work together to bring your ideas to life",
    "hero.download": "Download CV",
    "skills.frontend": "Frontend Development",
    "skills.frontend.desc": "React & Next.js • JavaScript & TypeScript • HTML5 & CSS3 • TailwindCSS & Styled Components • Responsive Design",
    "skills.tools": "Tools & Technologies",
    "skills.tools.desc": "Git & GitHub • Vite & Webpack • ESLint & Prettier • Vitest & Testing Library • Husky & Lint-staged",
    "skills.testing": "Low-Code",
    "skills.testing.desc": "Xano • Airtable • Make • UIBakery • Tilda • Carrd",
    "skills.other": "Design & Collaboration",
    "skills.other.desc": "Figma • Design Systems • Responsive Layouts",
    "projects.title": "Projects",
    "projects.eyebrow": "SELECTED DAMAGE",
    "projects.subtitle": "Building modern solutions using cutting-edge technologies",
    "projects.atlas.name": "ATLAS ANALYTICS Website",
    "projects.atlas.description": "Corporate website development and maintenance for ATLAS ANALYTICS. Creating a modern, responsive website with integration of various technologies to ensure functionality and performance.",
    "projects.to-done.name": "To-Done",
    "projects.partner-sites.name": "Partner Website",
    "projects.partner-sites.description": "Modern responsive website for a company partner. Full development from design to deployment using AI technologies.",
    "projects.ui-implementation.name": "UI Implementation",
    "projects.ui-implementation.description": "Pixel-perfect implementation of a Figma design. Building a clean, consistent, and user-friendly interface with responsive design. Frontend part of an educational project.",
    "projects.movie-picker.name": "Movie-Picker",
    "projects.movie-picker.description": "Interactive questionnaire that helps users choose a movie based on their preferences. The project includes a simple interactive form that leads the user to a result based on their choices.",
    "projects.random-game.name": "Flappy Bird",
    "projects.random-game.description": "Educational browser-based implementation of the classic Flappy Bird game. The game features a fully interactive interface, real-time scoring system, and game-over logic with result display. Player results are stored in local storage, allowing tracking of recent or best scores. Additional features such as animations and sound effects enhance the overall user experience.",
    "projects.to-done.description": "To-Done task management app helps users organize their work efficiently. The project includes task visualization in Kanban boards with drag-and-drop functionality, timelines for planning and tracking deadlines, and an intuitive interface for productivity management.",
    "projects.descriptionFallback": "Project description",
    "projects.stats.features": "FEATURES",
    "projects.stats.complete": "COMPLETE",
    "projects.stats.technologies": "TECHNOLOGIES",
    "projects.preview": "Preview",
    "projects.atlas.previewAlt": "ATLAS ANALYTICS Website Preview",
    "projects.partner-sites.previewAlt": "Signals.io Preview",
    "projects.ui-implementation.previewAlt": "Christmas Shop Preview",
    "projects.movie-picker.previewAlt": "Movie-Picker Preview",
    "projects.random-game.previewAlt": "Flappy Bird game preview",
    "projects.to-done.previewAlt": "To-Done Task Management Application Preview",
    "projects.viewCode": "View Code",
    "projects.viewWebsite": "View Website",
    "projects.learnMore": "Learn More",
    "projects.explore": "EXPLORE →",
    "projects.atlas.category": "WEB DESIGN",
    "projects.atlas.year": "2024",
    "projects.atlas.cardSummary": "Corporate site on Next.js — performance, scalability, and UX.",
    "projects.to-done.category": "APP DESIGN",
    "projects.to-done.year": "2024",
    "projects.to-done.cardSummary": "Kanban boards, timelines, drag-and-drop — task productivity.",
    "projects.partner-sites.category": "WEB DESIGN",
    "projects.partner-sites.year": "2024",
    "projects.partner-sites.cardSummary": "Partner website from design to deploy with a modern stack.",
    "projects.ui-implementation.category": "UI DESIGN",
    "projects.ui-implementation.year": "2024",
    "projects.ui-implementation.cardSummary": "Figma to pixel-perfect responsive UI — learning project.",
    "projects.movie-picker.category": "WEB DESIGN",
    "projects.movie-picker.year": "2024",
    "projects.movie-picker.cardSummary": "Interactive flow — choose a film from your preferences.",
    "projects.random-game.category": "GAME",
    "projects.random-game.year": "2024",
    "projects.random-game.cardSummary": "Flappy Bird–style game — obstacles, score, GitHub repo.",
    "skills.frontendDev": "Frontend Development",
    "skills.toolsTech": "Tools & Technologies",
    "skills.lowCode": "Low-Code",
  },
  es: {
    "nav.home": "Inicio",
    "nav.about": "Lo Que Hago",
    "nav.projects": "Proyectos",
    "nav.skills": "Habilidades",
    "nav.experience": "Experiencia",
    "nav.contact": "Contacto",
    "hero.title": "Victoria Nasonova",
    "hero.subtitle": "Desarrolladora Frontend",
    "hero.description": "Desarrollo interfaces web adaptativas con enfoque en código limpio, rendimiento y experiencia de usuario.",
    "about.title": "Lo Que Hago",
    "about.description": "• Desarrollo Frontend\n• Desarrollo Asistido por IA\n• Integración de API y Automatización\n• Implementación de UI",
    "about.item1": "Creo interfaces web responsivas y fáciles de usar. Mi enfoque está en construir soluciones claras, mantenibles y de alto rendimiento que se vean geniales y funcionen perfectamente en cualquier dispositivo.",
    "about.item2": "Diseño y desarrollo aplicaciones y landing pages escalables usando herramientas de IA para acelerar el desarrollo y mejorar la eficiencia. Integro soluciones con servicios backend para una gestión segura de datos y automatización.",
    "about.item3": "Conecto aplicaciones y servicios a través de integraciones de API. Estas automatizaciones ayudan a optimizar flujos de trabajo, sincronizar datos y reducir trabajos manuales repetitivos para los equipos.",
    "about.item4": "Transformo diseños de Figma en interfaces listas para producción con atención al detalle, accesibilidad y perfección de píxeles. Me preocupo por la usabilidad y consistencia en todas las pantallas y dispositivos.",
    "about.card1.title": "Desarrollo Frontend",
    "about.card2.title": "Desarrollo Asistido por IA",
    "about.card3.title": "Integración de API y Automatización", 
    "about.card4.title": "Implementación de UI",
    "skills.title": "Habilidades y Herramientas",
    "skills.description": "Frontend:\nJavaScript • TypeScript • React • Next.js • HTML5 • CSS3 • TailwindCSS • Vite\n\nTesting & Calidad de Código:\nESLint • Prettier • Vitest • React Testing Library • Git & GitHub\n\nNo-Code & Automatización:\nBubble • Tilda • WeWeb • Carrd • Xano • Airtable • Make\n\nDiseño & Colaboración:\nFigma • Sistemas de Diseño • Layouts Responsivos",
    "skills.certificates": "Certificados y Logros",
    "experience.title": "Experiencia y Educación",
    "experience.description": "Frontend Developer — ATLAS ANALYTICS (1 año)\n\n• Rediseñé y reconstruí el sitio web de la empresa desde cero, migrándolo de una plataforma no-code a un stack moderno con Next.js, mejorando rendimiento, escalabilidad y experiencia de usuario.\n• Diseñé y desarrollé sitios web para partners de extremo a extremo: desde la selección de conceptos UI/UX hasta la implementación de interfaces y la integración de servicios backend y flujos de automatización.\n• Mejoré la UX y la consistencia de aplicaciones internas mediante la reestructuración de interfaces, la unificación de patrones de diseño y la mejora de usabilidad en funcionalidades clave.\n• Construí dashboards y herramientas de reporting trabajando con datos de sistemas backend, y automaticé la entrega de datos a equipos internos para apoyar la toma de decisiones.\n• Colaboré en un entorno de equipo en proyectos reales, contribuyendo tanto a mejoras de producto como al desarrollo de nuevas funcionalidades.\n\nRS School — JavaScript / Frontend / React (1,5 años)\n\nCompleté un programa intensivo de frontend.\n\n• Trabajé con HTML, CSS, JavaScript, TypeScript, React y Next.js.\n• Construí aplicaciones desde cero usando tooling moderno (Vite, Webpack) e integré APIs REST con JavaScript asíncrono.\n• Implementé gestión de estado (Context API, Redux, Zustand), routing y data fetching.\n• Usé ESLint y Prettier para mantener la calidad del código, y adquirí experiencia en testing básico, debugging y optimización de rendimiento.\n• Colaboré en proyectos en equipo, participé en code reviews y seguí prácticas Agile.",
    "experience.item1": "Frontend Developer — ATLAS ANALYTICS (1 año)\n\n• Rediseñé y reconstruí el sitio web de la empresa desde cero, migrándolo de una plataforma no-code a un stack moderno con Next.js, mejorando rendimiento, escalabilidad y experiencia de usuario.\n• Diseñé y desarrollé sitios web para partners de extremo a extremo: desde la selección de conceptos UI/UX hasta la implementación de interfaces y la integración de servicios backend y flujos de automatización.\n• Mejoré la UX y la consistencia de aplicaciones internas mediante la reestructuración de interfaces, la unificación de patrones de diseño y la mejora de usabilidad en funcionalidades clave.\n• Construí dashboards y herramientas de reporting trabajando con datos de sistemas backend, y automaticé la entrega de datos a equipos internos para apoyar la toma de decisiones.\n• Colaboré en un entorno de equipo en proyectos reales, contribuyendo tanto a mejoras de producto como al desarrollo de nuevas funcionalidades.",
    "experience.item2": "Completé un programa intensivo de frontend en RS School (1,5 años)\n\n• Trabajé con HTML, CSS, JavaScript, TypeScript, React y Next.js.\n• Construí aplicaciones desde cero usando tooling moderno (Vite, Webpack) e integré APIs REST con JavaScript asíncrono.\n• Implementé gestión de estado (Context API, Redux, Zustand), routing y data fetching.\n• Usé ESLint y Prettier para mantener la calidad del código, y adquirí experiencia en testing básico, debugging y optimización de rendimiento.\n• Colaboré en proyectos en equipo, participé en code reviews y seguí prácticas Agile.",
    "contact.title": "Ponte en Contacto",
    "contact.description": "Trabajemos juntos para dar vida a tus ideas",
    "hero.download": "Descargar CV",
    "skills.frontend": "Desarrollo Frontend",
    "skills.frontend.desc": "React & Next.js • JavaScript & TypeScript • HTML5 & CSS3 • TailwindCSS & Styled Components • Responsive Design",
    "skills.tools": "Herramientas y Tecnologías",
    "skills.tools.desc": "Git & GitHub • Vite & Webpack • ESLint & Prettier • Vitest & Testing Library • Husky & Lint-staged",
    "skills.testing": "Low-Code",
    "skills.testing.desc": "Xano • Airtable • Make • UIBakery • Tilda • Carrd",
    "skills.other": "Diseño & Colaboración",
    "skills.other.desc": "Figma • Sistemas de Diseño • Layouts Responsivos",
    "projects.title": "Proyectos",
    "projects.eyebrow": "DAÑO SELECCIONADO",
    "projects.subtitle": "Desarrollo de soluciones modernas utilizando tecnologías avanzadas",
    "projects.atlas.name": "Sitio Web ATLAS ANALYTICS",
    "projects.atlas.description": "Desarrollo y mantenimiento del sitio web corporativo de ATLAS ANALYTICS. Creación de un sitio web moderno y responsivo con integración de diversas tecnologías para garantizar funcionalidad y rendimiento.",
    "projects.to-done.name": "To-Done",
    "projects.partner-sites.name": "Sitio Web de Socio",
    "projects.partner-sites.description": "Sitio web moderno y responsivo para un socio de la empresa. Desarrollo completo desde el diseño hasta el despliegue utilizando tecnologías de IA.",
    "projects.ui-implementation.name": "Implementación de UI",
    "projects.ui-implementation.description": "Implementación de un diseño de Figma con precisión pixel-perfect. Creación de una interfaz limpia, consistente y fácil de usar con diseño responsivo. Parte frontend de un proyecto educativo.",
    "projects.movie-picker.name": "Movie-Picker",
    "projects.movie-picker.description": "Cuestionario interactivo que ayuda a los usuarios a elegir una película según sus preferencias. El proyecto incluye un formulario simple e interactivo que lleva al usuario a un resultado basado en sus elecciones.",
    "projects.random-game.name": "Flappy Bird",
    "projects.random-game.description": "Implementación educativa en el navegador del clásico Flappy Bird. Incluye interfaz totalmente interactiva, sistema de puntuación en tiempo real y lógica de fin de partida con visualización de resultados. Las puntuaciones se guardan en el almacenamiento local para seguir las mejores o las más recientes. Animaciones y efectos de sonido mejoran la experiencia de usuario.",
    "projects.to-done.description": "La aplicación de gestión de tareas To-Done ayuda a los usuarios a organizar su trabajo de manera eficiente. El proyecto incluye visualización de tareas en tableros Kanban con funcionalidad de arrastrar y soltar, líneas de tiempo para planificación y seguimiento de plazos, y una interfaz intuitiva para gestionar la productividad.",
    "projects.descriptionFallback": "Descripción del proyecto",
    "projects.stats.features": "FUNCIONES",
    "projects.stats.complete": "COMPLETO",
    "projects.stats.technologies": "TECNOLOGÍAS",
    "projects.preview": "Vista previa",
    "projects.atlas.previewAlt": "Vista previa del sitio web ATLAS ANALYTICS",
    "projects.partner-sites.previewAlt": "Vista previa de Signals.io",
    "projects.ui-implementation.previewAlt": "Vista previa de Christmas Shop",
    "projects.movie-picker.previewAlt": "Vista previa de Movie-Picker",
    "projects.random-game.previewAlt": "Vista previa del juego Flappy Bird",
    "projects.to-done.previewAlt": "Vista previa de la aplicación de gestión de tareas To-Done",
    "projects.viewCode": "Ver Código",
    "projects.viewWebsite": "Ver Sitio Web",
    "projects.learnMore": "Más Detalles",
    "projects.explore": "EXPLORAR →",
    "projects.atlas.category": "DISEÑO WEB",
    "projects.atlas.year": "2024",
    "projects.atlas.cardSummary": "Sitio corporativo en Next.js — rendimiento, escalabilidad y UX.",
    "projects.to-done.category": "APP",
    "projects.to-done.year": "2024",
    "projects.to-done.cardSummary": "Kanban, líneas de tiempo, arrastrar y soltar — productividad.",
    "projects.partner-sites.category": "DISEÑO WEB",
    "projects.partner-sites.year": "2024",
    "projects.partner-sites.cardSummary": "Sitio para socio — del diseño al deploy con stack moderno.",
    "projects.ui-implementation.category": "UI",
    "projects.ui-implementation.year": "2024",
    "projects.ui-implementation.cardSummary": "De Figma a UI responsive pixel-perfect — proyecto educativo.",
    "projects.movie-picker.category": "DISEÑO WEB",
    "projects.movie-picker.year": "2024",
    "projects.movie-picker.cardSummary": "Cuestionario interactivo — elige una película según tus gustos.",
    "projects.random-game.category": "JUEGO",
    "projects.random-game.year": "2024",
    "projects.random-game.cardSummary": "Juego estilo Flappy Bird — obstáculos, puntuación, repo en GitHub.",
    "skills.frontendDev": "Desarrollo Frontend",
    "skills.toolsTech": "Herramientas y Tecnologías",
    "skills.lowCode": "Low-Code",
  },
  ru: {
    "nav.home": "Главная",
    "nav.about": "Что Я Делаю",
    "nav.projects": "Проекты",
    "nav.skills": "Навыки",
    "nav.experience": "Опыт",
    "nav.contact": "Контакты",
    "hero.title": "Виктория Насонова",
    "hero.subtitle": "Frontend Разработчик",
    "hero.description": "Разрабатываю адаптивные веб-интерфейсы с упором на чистый код, производительность и удобство пользователей.",
    "about.title": "Что Я Делаю",
    "about.description": "• Frontend Разработка\n• Разработка с поддержкой ИИ\n• Интеграция API и автоматизация\n• Реализация UI",
    "about.item1": "Создаю отзывчивые и удобные веб-интерфейсы. Мой фокус на построении четких, поддерживаемых и высокопроизводительных решений, которые отлично выглядят и работают безупречно на любом устройстве.",
    "about.item2": "Проектирую и разрабатываю масштабируемые приложения и лендинги с использованием ИИ-инструментов для ускорения разработки и повышения эффективности. Интегрирую решения с backend-сервисами для безопасного управления данными и автоматизации.",
    "about.item3": "Соединяю приложения и сервисы через API интеграции. Эти автоматизации помогают оптимизировать рабочие процессы, синхронизировать данные и сокращать повторяющуюся ручную работу для команд.",
    "about.item4": "Преобразую дизайны из Figma в готовые к продакшену интерфейсы с вниманием к деталям, доступности и пиксельному совершенству. Я забочусь о юзабилити и консистентности на всех экранах и устройствах.",
    "about.card1.title": "Frontend Разработка",
    "about.card2.title": "Разработка с поддержкой ИИ",
    "about.card3.title": "Интеграция API и автоматизация",
    "about.card4.title": "Реализация UI",
    "skills.title": "Навыки и Инструменты",
    "skills.description": "Frontend:\nJavaScript • TypeScript • React • Next.js • HTML5 • CSS3 • TailwindCSS • Vite\n\nТестирование и Качество Кода:\nESLint • Prettier • Vitest • React Testing Library • Git & GitHub\n\nNo-Code и Автоматизация:\nBubble • Tilda • WeWeb • Carrd • Xano • Airtable • Make\n\nДизайн и Сотрудничество:\nFigma • Дизайн Системы • Адаптивные Макеты",
    "skills.certificates": "Сертификаты и Достижения",
    "experience.title": "Опыт и Образование",
    "experience.description": "Frontend Developer — ATLAS ANALYTICS (1 год)\n\n• Полностью переработала и собрала сайт компании с нуля, мигрировав его с no-code платформы на современный стек с Next.js, улучшив производительность, масштабируемость и общий пользовательский опыт.\n• Проектировала и разрабатывала партнерские сайты end-to-end — от выбора UI/UX концепций до реализации интерфейсов и интеграции backend-сервисов и сценариев автоматизации.\n• Улучшила UX и консистентность внутренних приложений за счет реструктуризации интерфейсов, унификации дизайн-паттернов и повышения удобства ключевых функций.\n• Создавала дашборды и инструменты отчетности, работая с данными из backend-систем, и автоматизировала доставку данных внутренним командам для поддержки процессов принятия решений.\n• Работала в командной среде над реальными проектами, внося вклад как в улучшение продукта, так и в разработку новых функций.\n\nRS School — JavaScript / Frontend / React (1,5 года)\n\nПрошла интенсивную программу по frontend-разработке.\n\n• Работала с HTML, CSS, JavaScript, TypeScript, React и Next.js.\n• Создавала приложения с нуля, используя современный tooling (Vite, Webpack), и интегрировала REST API с помощью асинхронного JavaScript.\n• Реализовывала управление состоянием (Context API, Redux, Zustand), маршрутизацию и data fetching.\n• Использовала ESLint и Prettier для поддержания качества кода, а также получила опыт в базовом тестировании, отладке и оптимизации производительности.\n• Работала в командных проектах, участвовала в code review и следовала Agile-практикам.",
    "experience.item1": "Frontend Developer — ATLAS ANALYTICS (1 год)\n\n• Полностью переработала и собрала сайт компании с нуля, мигрировав его с no-code платформы на современный стек с Next.js, улучшив производительность, масштабируемость и общий пользовательский опыт.\n• Проектировала и разрабатывала партнерские сайты end-to-end — от выбора UI/UX концепций до реализации интерфейсов и интеграции backend-сервисов и сценариев автоматизации.\n• Улучшила UX и консистентность внутренних приложений за счет реструктуризации интерфейсов, унификации дизайн-паттернов и повышения удобства ключевых функций.\n• Создавала дашборды и инструменты отчетности, работая с данными из backend-систем, и автоматизировала доставку данных внутренним командам для поддержки процессов принятия решений.\n• Работала в командной среде над реальными проектами, внося вклад как в улучшение продукта, так и в разработку новых функций.",
    "experience.item2": "Прошла интенсивную 1,5-годичную программу по frontend-разработке в RS School\n\n• Работала с HTML, CSS, JavaScript, TypeScript, React и Next.js.\n• Создавала приложения с нуля, используя современный tooling (Vite, Webpack), и интегрировала REST API с помощью асинхронного JavaScript.\n• Реализовывала управление состоянием (Context API, Redux, Zustand), маршрутизацию и data fetching.\n• Использовала ESLint и Prettier для поддержания качества кода, а также получила опыт в базовом тестировании, отладке и оптимизации производительности.\n• Работала в командных проектах, участвовала в code review и следовала Agile-практикам.",
    "contact.title": "Свяжитесь со Мной",
    "contact.description": "Давайте работать вместе, чтобы воплотить ваши идеи в жизнь",
    "hero.download": "Скачать резюме",
    "skills.frontend": "Frontend Разработка",
    "skills.frontend.desc": "React & Next.js • JavaScript & TypeScript • HTML5 & CSS3 • TailwindCSS & Styled Components • Responsive Design",
    "skills.tools": "Инструменты и Технологии",
    "skills.tools.desc": "Git & GitHub • Vite & Webpack • ESLint & Prettier • Vitest & Testing Library • Husky & Lint-staged",
    "skills.testing": "Low-Code",
    "skills.testing.desc": "Xano • Airtable • Make • UIBakery • Tilda • Carrd",
    "skills.other": "Дизайн и Сотрудничество",
    "skills.other.desc": "Figma • Дизайн Системы • Адаптивные Макеты",
    "projects.title": "Проекты",
    "projects.eyebrow": "ОТОБРАННОЕ",
    "projects.subtitle": "Разработка современных решений с использованием передовых технологий",
    "projects.atlas.name": "Веб-сайт ATLAS ANALYTICS",
    "projects.atlas.description": "Разработка и поддержка корпоративного веб-сайта ATLAS ANALYTICS. Создание современного, адаптивного сайта с интеграцией различных технологий для обеспечения функциональности и производительности.",
    "projects.to-done.name": "To-Done",
    "projects.partner-sites.name": "Сайт Партнера",
    "projects.partner-sites.description": "Современный адаптивный веб-сайт для партнера компании. Полная разработка от дизайна до развертывания с использованием AI технологий.",
    "projects.ui-implementation.name": "Реализация UI",
    "projects.ui-implementation.description": "Верстка дизайна из Figma с пиксельной точностью. Создание чистого, последовательного и удобного интерфейса с адаптивным дизайном. Фронтенд часть учебного проекта.",
    "projects.movie-picker.name": "Movie-Picker",
    "projects.movie-picker.description": "Интерактивный опросник, который помогает пользователям выбрать фильм на основе их предпочтений. Проект включает простую, интерактивную анкету, которая ведет пользователя к результату на основе их выбора.",
    "projects.random-game.name": "Flappy Bird",
    "projects.random-game.description": "Образовательная браузерная реализация классической игры Flappy Bird. Полностью интерактивный интерфейс, подсчёт очков в реальном времени и логика окончания игры с отображением результата. Результаты игрока сохраняются в local storage — можно отслеживать последние и лучшие очки. Анимации и звуковые эффекты дополняют пользовательский опыт.",
    "projects.to-done.description": "Приложение для управления задачами To-Done помогает пользователям эффективно организовывать свою работу. Проект включает визуализацию задач в виде Канбан-досок с функцией перетаскивания, временные шкалы для планирования и отслеживания дедлайнов, а также интуитивный интерфейс для управления продуктивностью.",
    "projects.descriptionFallback": "Описание проекта",
    "projects.stats.features": "ФУНКЦИИ",
    "projects.stats.complete": "ГОТОВО",
    "projects.stats.technologies": "ТЕХНОЛОГИИ",
    "projects.preview": "Превью",
    "projects.atlas.previewAlt": "Превью веб-сайта ATLAS ANALYTICS",
    "projects.partner-sites.previewAlt": "Превью Signals.io",
    "projects.ui-implementation.previewAlt": "Превью Christmas Shop",
    "projects.movie-picker.previewAlt": "Превью Movie-Picker",
    "projects.random-game.previewAlt": "Превью игры Flappy Bird",
    "projects.to-done.previewAlt": "Превью приложения для управления задачами To-Done",
    "projects.viewCode": "Открыть код",
    "projects.viewWebsite": "Посмотреть сайт",
    "projects.learnMore": "Подробнее",
    "projects.explore": "СМОТРЕТЬ →",
    "projects.atlas.category": "ВЕБ-ДИЗАЙН",
    "projects.atlas.year": "2024",
    "projects.atlas.cardSummary": "Корпоративный сайт на Next.js — скорость, масштаб и UX.",
    "projects.to-done.category": "ПРИЛОЖЕНИЕ",
    "projects.to-done.year": "2024",
    "projects.to-done.cardSummary": "Канбан, таймлайны, drag-and-drop — задачи и продуктивность.",
    "projects.partner-sites.category": "ВЕБ-ДИЗАЙН",
    "projects.partner-sites.year": "2024",
    "projects.partner-sites.cardSummary": "Сайт партнёра — от дизайна до деплоя на современном стеке.",
    "projects.ui-implementation.category": "UI",
    "projects.ui-implementation.year": "2024",
    "projects.ui-implementation.cardSummary": "Figma в пиксель-перфект адаптивный интерфейс — учебный проект.",
    "projects.movie-picker.category": "ВЕБ-ДИЗАЙН",
    "projects.movie-picker.year": "2024",
    "projects.movie-picker.cardSummary": "Интерактивный опрос — выбор фильма по предпочтениям.",
    "projects.random-game.category": "ИГРА",
    "projects.random-game.year": "2024",
    "projects.random-game.cardSummary": "Игра в духе Flappy Bird — препятствия, счёт, репозиторий на GitHub.",
    "skills.frontendDev": "Frontend Разработка",
    "skills.toolsTech": "Инструменты и Технологии",
    "skills.lowCode": "Low-Code",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)["en"]] || key
  }

  useEffect(() => {
    const root = document.documentElement
    root.classList.toggle("lang-en", language === "en")
    root.classList.toggle("lang-es", language === "es")
    root.classList.toggle("lang-ru", language === "ru")
    root.lang = language === "en" ? "en" : language === "es" ? "es" : "ru"
    console.log("[Language] document lang/class updated:", language, root.className)
  }, [language])

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
