"use client"

import { createContext, useContext, useState, type ReactNode } from "react"

type Language = "en" | "es" | "ru"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    "nav.home": "Home",
    "nav.about": "What I Do",
    "nav.projects": "Projects",
    "nav.skills": "Skills",
    "nav.experience": "Experience",
    "nav.contact": "Contact",
    "hero.title": "Victoria Nasonova",
    "hero.subtitle": "Frontend & No-Code Developer",
    "hero.description": "Building modern, responsive web experiences that combine clean design, efficient code, and smart automation.",
    "hero.location": "Based in Argentina",
    "about.title": "What I Do",
    "about.description": "• Frontend Development\n• No-Code Development\n• API Integration & Automation\n• UI Implementation",
    "about.item1": "Frontend Development - I create responsive, user-friendly web interfaces using modern technologies like React, Next.js, TypeScript, and Tailwind CSS. My focus is on building clear, maintainable, and high-performance solutions that look great and work seamlessly on any device.",
    "about.item2": "No-Code Development - I design and develop scalable applications and landing pages using no-code platforms such as Bubble, Tilda, WeWeb, and Carrd. I integrate them with Xano or Airtable for secure data management and automation, delivering fast and efficient results for startups and internal tools.",
    "about.item3": "API Integration & Automation - I connect applications and services through API integrations using Make and custom solutions. These automations help optimize workflows, synchronize data, and reduce repetitive manual work for teams.",
    "about.item4": "UI Implementation - I transform Figma designs into production-ready interfaces with attention to detail, accessibility, and pixel perfection. I care about usability and consistency across all screens and devices.",
    "about.card1.title": "Frontend Development",
    "about.card2.title": "No-Code Development", 
    "about.card3.title": "API Integration & Automation",
    "about.card4.title": "UI Implementation",
    "skills.title": "Skills & Tools",
    "skills.description": "Frontend:\nJavaScript • TypeScript • React • Next.js • HTML5 • CSS3 • TailwindCSS • Vite\n\nTesting & Code Quality:\nESLint • Prettier • Vitest • React Testing Library • Git & GitHub\n\nNo-Code & Automation:\nBubble • Tilda • WeWeb • Carrd • Xano • Airtable • Make\n\nDesign & Collaboration:\nFigma • Design Systems • Responsive Layouts",
    "skills.certificates": "Certificates & Achievements",
    "experience.title": "Experience & Education",
    "experience.description": "Junior Frontend Developer — ATLAS ANALYTICS\nImproving internal no-code and low-code products, building interactive websites, integrating APIs with Xano, and automating workflows with Make.\n\nFrontend Apprenticeship (6 months)\nHands-on experience in developing responsive, interactive applications using React and modern web technologies.\n\nJavaScript & React Program — RS School (1 year)\nAdvanced training in frontend development, focusing on JavaScript, React, and clean code practices.",
    "experience.item1": "Junior Frontend Developer — ATLAS ANALYTICS\nImproving internal no-code and low-code products, building interactive websites, integrating APIs with Xano, and automating workflows with Make.",
    "experience.item2": "Frontend Apprenticeship (6 months)\nHands-on experience in developing responsive, interactive applications using React and modern web technologies.",
    "experience.item3": "JavaScript & React Program — RS School (1 year)\nAdvanced training in frontend development, focusing on JavaScript, React, and clean code practices.",
    "experience.footer": "Open to new opportunities in frontend and no-code development.\nPassionate about creating user-centric digital experiences that combine technology, design, and automation.",
    "contact.title": "Get In Touch",
    "contact.description": "Let's work together to bring your ideas to life",
    "hero.badge": "Available for work",
    "hero.download": "Download CV",
    "skills.frontend": "Frontend Development",
    "skills.frontend.desc": "React & Next.js • JavaScript & TypeScript • HTML5 & CSS3 • TailwindCSS & Styled Components • Responsive Design",
    "skills.tools": "Tools & Technologies",
    "skills.tools.desc": "Git & GitHub • Vite & Webpack • ESLint & Prettier • Vitest & Testing Library • Husky & Lint-staged",
    "skills.testing": "Low-Code",
    "skills.testing.desc": "Xano • Airtable • Make • UIBakery • Tilda • Carrd",
    "skills.other": "Design & Collaboration",
    "skills.other.desc": "Figma • Design Systems • Responsive Layouts",
    "projects.title": "My Projects",
    "projects.subtitle": "Building modern solutions using cutting-edge technologies",
    "projects.atlas.name": "ATLAS ANALYTICS Website",
    "projects.atlas.description": "Corporate website development and maintenance for ATLAS ANALYTICS. Creating a modern, responsive website with integration of various technologies to ensure functionality and performance.",
    "projects.partner.name": "Partner Website",
    "projects.partner.description": "Modern responsive website development for business partners. Complete development from design to deployment using cutting-edge technologies.",
    "projects.ui.name": "UI Implementation",
    "projects.ui.description": "Pixel-perfect Figma design implementation. Creating clean, consistent, and user-friendly interfaces with responsive design principles. Frontend part of an educational project.",
    "projects.viewCode": "View Code",
    "projects.viewWebsite": "View Website",
    "projects.learnMore": "Learn More",
    "skills.frontendDev": "Frontend Development",
    "skills.toolsTech": "Tools & Technologies",
    "skills.lowCode": "Low-Code",
  },
  es: {
    "nav.home": "Inicio",
    "nav.about": "Lo Que Hago",
    "nav.projects": "Proyectos",
    "nav.skills": "Habilidades",
    "nav.experience": "Experiencia",
    "nav.contact": "Contacto",
    "hero.title": "Victoria Nasonova",
    "hero.subtitle": "Desarrolladora Frontend & No-Code",
    "hero.description": "Construyendo experiencias web modernas y responsivas que combinan diseño limpio, código eficiente y automatización inteligente.",
    "hero.location": "Basada en Argentina",
    "about.title": "Lo Que Hago",
    "about.description": "• Desarrollo Frontend\n• Desarrollo No-Code\n• Integración de API y Automatización\n• Implementación de UI",
    "about.item1": "Desarrollo Frontend - Creo interfaces web responsivas y fáciles de usar usando tecnologías modernas como React, Next.js, TypeScript y Tailwind CSS. Mi enfoque está en construir soluciones claras, mantenibles y de alto rendimiento que se vean geniales y funcionen perfectamente en cualquier dispositivo.",
    "about.item2": "Desarrollo No-Code - Diseño y desarrollo aplicaciones y landing pages escalables usando plataformas no-code como Bubble, Tilda, WeWeb y Carrd. Las integro con Xano o Airtable para gestión segura de datos y automatización, entregando resultados rápidos y eficientes para startups y herramientas internas.",
    "about.item3": "Integración de API y Automatización - Conecto aplicaciones y servicios a través de integraciones de API usando Make y soluciones personalizadas. Estas automatizaciones ayudan a optimizar flujos de trabajo, sincronizar datos y reducir trabajos manuales repetitivos para los equipos.",
    "about.item4": "Implementación de UI - Transformo diseños de Figma en interfaces listas para producción con atención al detalle, accesibilidad y perfección de píxeles. Me preocupo por la usabilidad y consistencia en todas las pantallas y dispositivos.",
    "about.card1.title": "Desarrollo Frontend",
    "about.card2.title": "Desarrollo No-Code",
    "about.card3.title": "Integración de API y Automatización", 
    "about.card4.title": "Implementación de UI",
    "skills.title": "Habilidades y Herramientas",
    "skills.description": "Frontend:\nJavaScript • TypeScript • React • Next.js • HTML5 • CSS3 • TailwindCSS • Vite\n\nTesting & Calidad de Código:\nESLint • Prettier • Vitest • React Testing Library • Git & GitHub\n\nNo-Code & Automatización:\nBubble • Tilda • WeWeb • Carrd • Xano • Airtable • Make\n\nDiseño & Colaboración:\nFigma • Sistemas de Diseño • Layouts Responsivos",
    "skills.certificates": "Certificados y Logros",
    "experience.title": "Experiencia y Educación",
    "experience.description": "Desarrolladora Frontend Junior — ATLAS ANALYTICS\nMejoro productos internos no-code y low-code, construyo sitios web interactivos, integro APIs con Xano y automatizo flujos de trabajo con Make.\n\nPasantía en Frontend (6 meses)\nExperiencia práctica desarrollando aplicaciones responsivas e interactivas usando React y tecnologías web modernas.\n\nPrograma JavaScript & React — RS School (1 año)\nFormación avanzada en desarrollo frontend, enfocándome en JavaScript, React y prácticas de código limpio.",
    "experience.item1": "Desarrolladora Frontend Junior — ATLAS ANALYTICS\nMejoro productos internos no-code y low-code, construyo sitios web interactivos, integro APIs con Xano y automatizo flujos de trabajo con Make.",
    "experience.item2": "Pasantía en Frontend (6 meses)\nExperiencia práctica desarrollando aplicaciones responsivas e interactivas usando React y tecnologías web modernas.",
    "experience.item3": "Programa JavaScript & React — RS School (1 año)\nFormación avanzada en desarrollo frontend, enfocándome en JavaScript, React y prácticas de código limpio.",
    "experience.footer": "Abierta a nuevas oportunidades en desarrollo frontend y no-code.\nApasionada por crear experiencias digitales centradas en el usuario que combinen tecnología, diseño y automatización.",
    "contact.title": "Ponte en Contacto",
    "contact.description": "Trabajemos juntos para dar vida a tus ideas",
    "hero.badge": "Disponible para trabajar",
    "hero.download": "Descargar CV",
    "skills.frontend": "Desarrollo Frontend",
    "skills.frontend.desc": "React & Next.js • JavaScript & TypeScript • HTML5 & CSS3 • TailwindCSS & Styled Components • Responsive Design",
    "skills.tools": "Herramientas y Tecnologías",
    "skills.tools.desc": "Git & GitHub • Vite & Webpack • ESLint & Prettier • Vitest & Testing Library • Husky & Lint-staged",
    "skills.testing": "Low-Code",
    "skills.testing.desc": "Xano • Airtable • Make • UIBakery • Tilda • Carrd",
    "skills.other": "Diseño & Colaboración",
    "skills.other.desc": "Figma • Sistemas de Diseño • Layouts Responsivos",
    "projects.title": "Mis Proyectos",
    "projects.subtitle": "Desarrollo de soluciones modernas utilizando tecnologías avanzadas",
    "projects.atlas.name": "Sitio Web ATLAS ANALYTICS",
    "projects.atlas.description": "Desarrollo y mantenimiento del sitio web corporativo de ATLAS ANALYTICS. Creación de un sitio web moderno y responsivo con integración de diversas tecnologías para garantizar funcionalidad y rendimiento.",
    "projects.partner.name": "Sitio Web de Socio",
    "projects.partner.description": "Desarrollo de sitios web modernos y responsivos para socios comerciales. Desarrollo completo desde el diseño hasta el despliegue utilizando tecnologías de vanguardia.",
    "projects.ui.name": "Implementación de UI",
    "projects.ui.description": "Implementación de diseños de Figma con precisión pixel-perfect. Creación de interfaces limpias, consistentes y amigables con diseño responsivo. Parte frontend de un proyecto educativo.",
    "projects.viewCode": "Ver Código",
    "projects.viewWebsite": "Ver Sitio Web",
    "projects.learnMore": "Más Detalles",
    "skills.frontendDev": "Desarrollo Frontend",
    "skills.toolsTech": "Herramientas y Tecnologías",
    "skills.lowCode": "Low-Code",
  },
  ru: {
    "nav.home": "Главная",
    "nav.about": "Что Я Делаю",
    "nav.projects": "Проекты",
    "nav.skills": "Навыки",
    "nav.experience": "Опыт",
    "nav.contact": "Контакты",
    "hero.title": "Виктория Насонова",
    "hero.subtitle": "Frontend & No-Code Разработчик",
    "hero.description": "Создание современных адаптивных веб-интерфейсов, сочетающих чистый дизайн, эффективный код и интеллектуальную автоматизацию.",
    "hero.location": "Нахожусь в Аргентине",
    "about.title": "Что Я Делаю",
    "about.description": "• Frontend Разработка\n• No-Code Разработка\n• Интеграция API и автоматизация\n• Реализация UI",
    "about.item1": "Frontend Разработка - Я создаю отзывчивые и удобные веб-интерфейсы, используя современные технологии, такие как React, Next.js, TypeScript и Tailwind CSS. Мой фокус на построении четких, поддерживаемых и высокопроизводительных решений, которые отлично выглядят и работают безупречно на любом устройстве.",
    "about.item2": "No-Code Разработка - Я проектирую и разрабатываю масштабируемые приложения и лендинг-страницы, используя no-code платформы, такие как Bubble, Tilda, WeWeb и Carrd. Интегрирую их с Xano или Airtable для безопасного управления данными и автоматизации, обеспечивая быстрые и эффективные результаты для стартапов и внутренних инструментов.",
    "about.item3": "Интеграция API и автоматизация - Я соединяю приложения и сервисы через API интеграции с использованием Make и кастомных решений. Эти автоматизации помогают оптимизировать рабочие процессы, синхронизировать данные и сокращать повторяющуюся ручную работу для команд.",
    "about.item4": "Реализация UI - Я преобразую дизайны из Figma в готовые к продакшену интерфейсы с вниманием к деталям, доступности и пиксельному совершенству. Я забочусь о юзабилити и консистентности на всех экранах и устройствах.",
    "about.card1.title": "Frontend Разработка",
    "about.card2.title": "No-Code Разработка",
    "about.card3.title": "Интеграция API и автоматизация",
    "about.card4.title": "Реализация UI",
    "skills.title": "Навыки и Инструменты",
    "skills.description": "Frontend:\nJavaScript • TypeScript • React • Next.js • HTML5 • CSS3 • TailwindCSS • Vite\n\nТестирование и Качество Кода:\nESLint • Prettier • Vitest • React Testing Library • Git & GitHub\n\nNo-Code и Автоматизация:\nBubble • Tilda • WeWeb • Carrd • Xano • Airtable • Make\n\nДизайн и Сотрудничество:\nFigma • Дизайн Системы • Адаптивные Макеты",
    "skills.certificates": "Сертификаты и Достижения",
    "experience.title": "Опыт и Образование",
    "experience.description": "Младший Frontend Разработчик — ATLAS ANALYTICS\nУлучшаю внутренние no-code и low-code продукты, создаю интерактивные веб-сайты, интегрирую API с Xano и автоматизирую рабочие процессы с Make.\n\nСтажировка во Frontend (6 месяцев)\nПрактический опыт в разработке отзывчивых интерактивных приложений с использованием React и современных веб-технологий.\n\nПрограмма JavaScript & React — RS School (1 год)\nПродвинутое обучение в области frontend разработки, фокусируясь на JavaScript, React и практиках написания чистого кода.",
    "experience.item1": "Младший Frontend Разработчик — ATLAS ANALYTICS\nУлучшаю внутренние no-code и low-code продукты, создаю интерактивные веб-сайты, интегрирую API с Xano и автоматизирую рабочие процессы с Make.",
    "experience.item2": "Стажировка во Frontend (6 месяцев)\nПрактический опыт в разработке отзывчивых интерактивных приложений с использованием React и современных веб-технологий.",
    "experience.item3": "Программа JavaScript & React — RS School (1 год)\nПродвинутое обучение в области frontend разработки, фокусируясь на JavaScript, React и практиках написания чистого кода.",
    "experience.footer": "Открыта для новых возможностей в frontend и no-code разработке.\nУвлечена созданием ориентированных на пользователя цифровых решений, сочетающих технологии, дизайн и автоматизацию.",
    "contact.title": "Свяжитесь со Мной",
    "contact.description": "Давайте работать вместе, чтобы воплотить ваши идеи в жизнь",
    "hero.badge": "Доступна для работы",
    "hero.download": "Скачать резюме",
    "skills.frontend": "Frontend Разработка",
    "skills.frontend.desc": "React & Next.js • JavaScript & TypeScript • HTML5 & CSS3 • TailwindCSS & Styled Components • Responsive Design",
    "skills.tools": "Инструменты и Технологии",
    "skills.tools.desc": "Git & GitHub • Vite & Webpack • ESLint & Prettier • Vitest & Testing Library • Husky & Lint-staged",
    "skills.testing": "Low-Code",
    "skills.testing.desc": "Xano • Airtable • Make • UIBakery • Tilda • Carrd",
    "skills.other": "Дизайн и Сотрудничество",
    "skills.other.desc": "Figma • Дизайн Системы • Адаптивные Макеты",
    "projects.title": "Мои Проекты",
    "projects.subtitle": "Разработка современных решений с использованием передовых технологий",
    "projects.atlas.name": "Веб-сайт ATLAS ANALYTICS",
    "projects.atlas.description": "Разработка и поддержка корпоративного веб-сайта ATLAS ANALYTICS. Создание современного, адаптивного сайта с интеграцией различных технологий для обеспечения функциональности и производительности.",
    "projects.partner.name": "Сайт Партнера",
    "projects.partner.description": "Создание современных адаптивных веб-сайтов для партнеров компании. Полная разработка от дизайна до развертывания с использованием современных технологий.",
    "projects.ui.name": "Реализация UI",
    "projects.ui.description": "Воплощение дизайнов из Figma с пиксельной точностью. Создание чистых, последовательных и удобных интерфейсов с адаптивным дизайном. Фронтенд часть учебного проекта.",
    "projects.viewCode": "Открыть код",
    "projects.viewWebsite": "Посмотреть сайт",
    "projects.learnMore": "Подробнее",
    "skills.frontendDev": "Frontend Разработка",
    "skills.toolsTech": "Инструменты и Технологии",
    "skills.lowCode": "Low-Code",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)["en"]] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
