"use client"

import { createContext, useContext, useState, type ReactNode } from "react"

type Language = "en" | "es" | "ru"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    "nav.home": "Home",
    "nav.about": "What I Do",
    "nav.projects": "Projects",
    "nav.skills": "Skills",
    "nav.experience": "Experience",
    "nav.contact": "Contact",
    "hero.title": "Victoria Nasonova",
    "hero.subtitle": "Frontend Developer creating beautiful and functional user experiences",
    "hero.location": "Based in Argentina",
    "about.title": "What I Do",
    "about.description": "• Web Development\n• Low-Code Projects\n• API Integration & Automation\n• UI Implementation",
    "about.item1": "Web Development - Create modern, responsive websites using HTML, CSS, JavaScript, and frameworks like React or Next.js.",
    "about.item2": "Low-Code Projects - Build functional and visually appealing web apps using Bubble, Tilda, WeWeb, Carrd, and UI Bakery — integrating Xano for backend logic and data management.",
    "about.item3": "API Integration & Automation - Connect frontend, databases, and automations — integrating APIs and using Make to streamline workflows and ensure seamless data flow between platforms.",
    "about.item4": "UI Implementation - Bring Figma designs to life with pixel-perfect precision, ensuring clean, consistent, and user-friendly interfaces.",
    "about.card1.title": "Web Development",
    "about.card2.title": "Low-Code Projects", 
    "about.card3.title": "API Integration & Automation",
    "about.card4.title": "UI Implementation",
    "skills.title": "Skills & Technologies",
    "skills.description": "Proficient in modern frontend technologies and tools, with a focus on creating scalable and maintainable code.",
    "skills.certificates": "Certificates & Achievements",
    "experience.title": "Experience & Education",
    "experience.description": "• Junior Frontend Developer at ATLAS ANALYTICS — enhancing internal no-code/low-code products, building websites, integrating APIs with Xano, and automating workflows with Make.\n• 6-month apprenticeship in frontend development\n• 1-year JavaScript & React program at RS School",
    "experience.item1": "Junior Frontend Developer at ATLAS ANALYTICS — enhancing internal no-code/low-code products, building websites, integrating APIs with Xano, and automating workflows with Make.",
    "experience.item2": "6-month apprenticeship in frontend development",
    "experience.item3": "1-year JavaScript & React program at RS School",
    "contact.title": "Get In Touch",
    "contact.description": "Let's work together to bring your ideas to life",
    "hero.badge": "Available for work",
    "hero.download": "Download CV",
    "skills.frontend": "Frontend",
    "skills.frontend.desc": "React, Next.js, TypeScript, JavaScript, HTML5, CSS3, Tailwind CSS",
    "skills.tools": "Tools & Libraries",
    "skills.tools.desc": "Git, Webpack, Vite, Framer Motion, Zustand, React Query",
    "skills.testing": "Testing",
    "skills.testing.desc": "Jest, React Testing Library, Cypress, Playwright",
    "skills.other": "Other",
    "skills.other.desc": "Node.js, Express, MongoDB, PostgreSQL, Docker",
    "projects.title": "My Projects",
    "projects.subtitle": "Building modern solutions using cutting-edge technologies",
    "projects.atlas.name": "ATLAS ANALYTICS Website",
    "projects.atlas.description": "Corporate website development and maintenance for ATLAS ANALYTICS. Creating a modern, responsive website with integration of various technologies to ensure functionality and performance.",
    "projects.partner.name": "Partner Website",
    "projects.partner.description": "Modern responsive website development for business partners. Complete development from design to deployment using cutting-edge technologies.",
    "projects.ui.name": "UI Implementation",
    "projects.ui.description": "Pixel-perfect Figma design implementation. Creating clean, consistent, and user-friendly interfaces with responsive design principles. Frontend part of an educational project.",
    "projects.viewCode": "View Code",
    "projects.viewWebsite": "View Website",
    "projects.learnMore": "Learn More",
    "skills.frontendDev": "Frontend Development",
    "skills.toolsTech": "Tools & Technologies",
    "skills.lowCode": "Low-Code",
  },
  es: {
    "nav.home": "Inicio",
    "nav.about": "Lo Que Hago",
    "nav.projects": "Proyectos",
    "nav.skills": "Habilidades",
    "nav.experience": "Experiencia",
    "nav.contact": "Contacto",
    "hero.title": "Victoria Nasonova",
    "hero.subtitle": "Desarrolladora Frontend creando experiencias de usuario hermosas y funcionales",
    "hero.location": "Basada en Argentina",
    "about.title": "Lo Que Hago",
    "about.description": "• Desarrollo Web\n• Proyectos Low-Code\n• Integración de API y Automatización\n• Implementación de UI",
    "about.item1": "Desarrollo Web - Creo sitios web modernos y responsivos usando HTML, CSS, JavaScript y frameworks como React o Next.js.",
    "about.item2": "Proyectos Low-Code - Construyo aplicaciones web funcionales y visualmente atractivas usando Bubble, Tilda, WeWeb, Carrd y UI Bakery — integrando Xano para lógica backend y gestión de datos.",
    "about.item3": "Integración de API y Automatización - Conecto frontend, bases de datos y automatizaciones — integrando APIs y usando Make para optimizar flujos de trabajo y asegurar flujo de datos sin problemas entre plataformas.",
    "about.item4": "Implementación de UI - Doy vida a diseños de Figma con precisión pixel-perfect, asegurando interfaces limpias, consistentes y amigables para el usuario.",
    "about.card1.title": "Desarrollo Web",
    "about.card2.title": "Proyectos Low-Code",
    "about.card3.title": "Integración de API y Automatización", 
    "about.card4.title": "Implementación de UI",
    "skills.title": "Habilidades y Tecnologías",
    "skills.description": "Experto en tecnologías y herramientas frontend modernas, con enfoque en crear código escalable y mantenible.",
    "skills.certificates": "Certificados y Logros",
    "experience.title": "Experiencia y Educación",
    "experience.description": "• Desarrolladora Frontend Junior en ATLAS ANALYTICS — mejorando productos internos no-code/low-code, construyendo sitios web, integrando APIs con Xano y automatizando flujos de trabajo con Make.\n• Pasantía de 6 meses en desarrollo frontend\n• Programa de 1 año de JavaScript & React en RS School",
    "experience.item1": "Desarrolladora Frontend Junior en ATLAS ANALYTICS — mejorando productos internos no-code/low-code, construyendo sitios web, integrando APIs con Xano y automatizando flujos de trabajo con Make.",
    "experience.item2": "Pasantía de 6 meses en desarrollo frontend",
    "experience.item3": "Programa de 1 año de JavaScript & React en RS School",
    "contact.title": "Ponte en Contacto",
    "contact.description": "Trabajemos juntos para dar vida a tus ideas",
    "hero.badge": "Disponible para trabajar",
    "hero.download": "Descargar CV",
    "skills.frontend": "Frontend",
    "skills.frontend.desc": "React, Next.js, TypeScript, JavaScript, HTML5, CSS3, Tailwind CSS",
    "skills.tools": "Herramientas y Librerías",
    "skills.tools.desc": "Git, Webpack, Vite, Framer Motion, Zustand, React Query",
    "skills.testing": "Testing",
    "skills.testing.desc": "Jest, React Testing Library, Cypress, Playwright",
    "skills.other": "Otros",
    "skills.other.desc": "Node.js, Express, MongoDB, PostgreSQL, Docker",
    "projects.title": "Mis Proyectos",
    "projects.subtitle": "Desarrollo de soluciones modernas utilizando tecnologías avanzadas",
    "projects.atlas.name": "Sitio Web ATLAS ANALYTICS",
    "projects.atlas.description": "Desarrollo y mantenimiento del sitio web corporativo de ATLAS ANALYTICS. Creación de un sitio web moderno y responsivo con integración de diversas tecnologías para garantizar funcionalidad y rendimiento.",
    "projects.partner.name": "Sitio Web de Socio",
    "projects.partner.description": "Desarrollo de sitios web modernos y responsivos para socios comerciales. Desarrollo completo desde el diseño hasta el despliegue utilizando tecnologías de vanguardia.",
    "projects.ui.name": "Implementación de UI",
    "projects.ui.description": "Implementación de diseños de Figma con precisión pixel-perfect. Creación de interfaces limpias, consistentes y amigables con diseño responsivo. Parte frontend de un proyecto educativo.",
    "projects.viewCode": "Ver Código",
    "projects.viewWebsite": "Ver Sitio Web",
    "projects.learnMore": "Más Detalles",
    "skills.frontendDev": "Desarrollo Frontend",
    "skills.toolsTech": "Herramientas y Tecnologías",
    "skills.lowCode": "Low-Code",
  },
  ru: {
    "nav.home": "Главная",
    "nav.about": "Что Я Делаю",
    "nav.projects": "Проекты",
    "nav.skills": "Навыки",
    "nav.experience": "Опыт",
    "nav.contact": "Контакты",
    "hero.title": "Виктория Насонова",
    "hero.subtitle": "Frontend разработчик, создающий красивые и функциональные пользовательские интерфейсы",
    "hero.location": "Находится в Аргентине",
    "about.title": "Что Я Делаю",
    "about.description": "• Веб-разработка\n• Low-Code проекты\n• Интеграция API и автоматизация\n• Реализация UI",
    "about.item1": "Веб-разработка - Создаю современные, адаптивные веб-сайты используя HTML, CSS, JavaScript и фреймворки как React или Next.js.",
    "about.item2": "Low-Code проекты - Создаю функциональные и визуально привлекательные веб-приложения используя Bubble, Tilda, WeWeb, Carrd и UI Bakery — интегрируя Xano для backend логики и управления данными.",
    "about.item3": "Интеграция API и автоматизация - Соединяю frontend, базы данных и автоматизацию — интегрируя API и используя Make для оптимизации рабочих процессов и обеспечения бесшовного потока данных между платформами.",
    "about.item4": "Реализация UI - Воплощаю дизайны из Figma с пиксельной точностью, обеспечивая чистые, последовательные и удобные интерфейсы.",
    "about.card1.title": "Веб-разработка",
    "about.card2.title": "Low-Code проекты",
    "about.card3.title": "Интеграция API и автоматизация",
    "about.card4.title": "Реализация UI",
    "skills.title": "Навыки и Технологии",
    "skills.description": "Владею современными frontend технологиями и инструментами, с фокусом на создание масштабируемого и поддерживаемого кода.",
    "skills.certificates": "Сертификаты и Достижения",
    "experience.title": "Опыт и Образование",
    "experience.description": "• Младший Frontend разработчик в ATLAS ANALYTICS — улучшение внутренних no-code/low-code продуктов, создание веб-сайтов, интеграция API с Xano и автоматизация рабочих процессов с Make.\n• 6-месячная стажировка в области frontend разработки\n• 1-годичная программа JavaScript & React в RS School",
    "experience.item1": "Младший Frontend разработчик в ATLAS ANALYTICS — улучшение внутренних no-code/low-code продуктов, создание веб-сайтов, интеграция API с Xano и автоматизация рабочих процессов с Make.",
    "experience.item2": "6-месячная стажировка в области frontend разработки",
    "experience.item3": "1-годичная программа JavaScript & React в RS School",
    "contact.title": "Свяжитесь со Мной",
    "contact.description": "Давайте работать вместе, чтобы воплотить ваши идеи в жизнь",
    "hero.badge": "Доступен для работы",
    "hero.download": "Скачать резюме",
    "skills.frontend": "Frontend",
    "skills.frontend.desc": "React, Next.js, TypeScript, JavaScript, HTML5, CSS3, Tailwind CSS",
    "skills.tools": "Инструменты и Библиотеки",
    "skills.tools.desc": "Git, Webpack, Vite, Framer Motion, Zustand, React Query",
    "skills.testing": "Тестирование",
    "skills.testing.desc": "Jest, React Testing Library, Cypress, Playwright",
    "skills.other": "Прочее",
    "skills.other.desc": "Node.js, Express, MongoDB, PostgreSQL, Docker",
    "projects.title": "Мои Проекты",
    "projects.subtitle": "Разработка современных решений с использованием передовых технологий",
    "projects.atlas.name": "Веб-сайт ATLAS ANALYTICS",
    "projects.atlas.description": "Разработка и поддержка корпоративного веб-сайта ATLAS ANALYTICS. Создание современного, адаптивного сайта с интеграцией различных технологий для обеспечения функциональности и производительности.",
    "projects.partner.name": "Сайт Партнера",
    "projects.partner.description": "Создание современных адаптивных веб-сайтов для партнеров компании. Полная разработка от дизайна до развертывания с использованием современных технологий.",
    "projects.ui.name": "Реализация UI",
    "projects.ui.description": "Воплощение дизайнов из Figma с пиксельной точностью. Создание чистых, последовательных и удобных интерфейсов с адаптивным дизайном. Фронтенд часть учебного проекта.",
    "projects.viewCode": "Открыть код",
    "projects.viewWebsite": "Посмотреть сайт",
    "projects.learnMore": "Подробнее",
    "skills.frontendDev": "Frontend Разработка",
    "skills.toolsTech": "Инструменты и Технологии",
    "skills.lowCode": "Low-Code",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)["en"]] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
